### ISSUE TITLE
Graphical Improvements for the RAM, customizability Improvements for the ROM

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#120]
So, now we have got a RAM component.

Great huh?

Well, not quite. The ram is certainly powerful, but I feel like it's significantly lacking graphically. I was kind of hoping the RAM would have the same appearance as the rom, making both elements interchangable, and relatable. This would also mean RAM would give a programmer some form of visual feedback to it's state, instead of a "core dump", which is hardly user friendly. I think that a RAM component should allow the user to see it's data directly on a table, like it's seen on the ROM. better yet, it would allow users to directly edit RAM for debugging.

While on the topic of ROMs, the ROM could also see an overhaul. Seeing how the RAM can have it's address and data bit width customized, why not the ROM? Both components should be considered equals, as they both serve equal purposes, storing data for latter use.

**Comment by satu0king** [comment]
The RAM cannot have the same UI as the current ROM because the amount of memory the RAM supports is huge. Having said that, yes I think it is high time that the ROM gets an overhaul now. It was implemented as a solution to build the SAP-1 but now we are way past that! 

@jbox144 what do you think of the DMA access pin discussed in #118 ? I think that is a solution that will meet everyone's requirements. Then we can simply create any module we need using the DMA pin and plug it on the RAM as needed. I also thing it is fairly easy to implement once we get the design right.

**Comment by jbox144** [comment]
> The RAM cannot have the same UI as the current ROM because the amount of memory the RAM supports is huge. Having said that, yes I think it is high time that the ROM gets an overhaul now. It was implemented as a solution to build the SAP-1 but now we are way past that!
> 
> @jbox144 what do you think of the DMA access pin discussed in #118 ? I think that is a solution that will meet everyone's requirements. Then we can simply create any module we need using the DMA pin and plug it on the RAM as needed. I also thing it is fairly easy to implement once we get the design right.

I like the solution, and I also think the RAM deserves it's own DMA pin too. Like I said, both components deserve equal attention.
