### ISSUE TITLE
Backspace deleting components while editing labels bug re-occured

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#121]
This bug was found a while back, and patched, but has recently reoccured. 

In summary, at random, pressing the backspace while editing a component's tag deletes the part, when the part should not be deleted while the tag is being edited.

**Comment by satu0king** [comment]
Yes, in the attempt to fix this issue another issue came up - people were not able to delete at all! So temporarily the fix has been reverted.

**Comment by jbox144** [comment]
> Yes, in the attempt to fix this issue another issue came up - people were not able to delete at all! So temporarily the fix has been reverted.

If it helps, the original patch's bug of not being able to delete components could be fixed by dragging a new component in

**Comment by satu0king** [comment]
> > Yes, in the attempt to fix this issue another issue came up - people were not able to delete at all! So temporarily the fix has been reverted.
> 
> If it helps, the original patch's bug of not being able to delete components could be fixed by dragging a new component in

Thank you, I actually happen to know what is happening but not sure how to fix it. It is one these awkward situations where you know exactly what the bug is but still no idea on how to fix it! 

Basically backspace has to be delete because Mac OS binds backspace to delete. Now backspace is also used as actual backspace in text elements in property menu. So the temporary fix I did was that as long as something is selected in property menu, do not allow deletion in the simulator. But then what happened was sometimes the property menu was not getting deselected, so the simulator element was still not getting deleted. When you drag a new element in, this thing was reset automatically by the browser, so now you can delete it. 

As of now, as long as the mouse is not within the simulator region, backspace cannot delete, maybe this is what you can use to avoid the bug for now.

**Comment by Shivansh2407** [comment]
@satu0king #952 fixes this issue . Please reopen this issue and review the PR 👍
