### ISSUE TITLE
fixing zooming issue

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1308]
**Describe the bug**
zoom doesn't work from keyboard
with ctrl + = or ctrl + - buttons

**To Reproduce**
1. Go to 'https://circuitverse.org/simulator'
2. Click on 'ctrl + = '
3.notice that zoom doesn't work

**Additional context**

1. grid doesn't update after zooming from the keyboard

1. the user has to click on the bard before zooming 

1. the + , and - buttons should  also zoom 

**Are you working on this issue? (Yes/No)**
YES

**Comment by Shivansh2407** [comment]
The zoom actually works in the simulation area but after pressing CTRL + =/(+) you need to click on the grid/simulation area to see the results .
Steps :
1. Click on the Grid
2. Press CTRL + = 
3. Click on the Grid after pressing the keys to see the result.
It actually needs to be fixed because not everyone would be aware that we need to click after pressing the keys.

**Comment by mahmodHammad** [comment]
> The zoom actually works in the simulation area but after pressing CTRL + =/(+) you need to click on the grid/simulation area to see the results .
> Steps :
> 
> 1. Click on the Grid
> 2. Press CTRL + =
> 3. Click on the Grid after pressing the keys to see the result.
>    This actually needs to be fixed because not everyone would be aware that we need to click after pressing the keys.

aha after i put a component i fount it zooms 
but

**Comment by aayush-05** [comment]
Agreed @Shivansh2407 . @mahmodHammad maybe change the Issue title to better fit the problem.
