### ISSUE TITLE
Add a property to components such as decoders that sets the gap between the pins.

### ISSUE THREAD

**Issue by HypheX** [CircuitVerse/CircuitVerse#14]
Decoders, encoders, multiplexers, de-multiplexers.

They always have a 2-square gap between the pins. It would be really useful to be able to set the gap between the pins as to avoid additional wiring. #

**Comment by satu0king** [comment]
This can be done as follows

Add an additional attribute called spacing type in the objects. Set it to 1 for 2-square gap and 0 for 1-square gap. This has to be implemented using mutableProperties attribute. When the property value is changed, delete the object and create a new one at the same position. This will be neat and easy. 

- [ ] Add attribute `spacingType` set it according to the current default type. For example, for Multiplexer, current default is `2` for control signal size 1,2,3 and `1` after 3. 
- [ ] Make appropriate changes `changeControlSignalSize()`
- [ ] Add a property in `mutableProperties` so that it shows on the property menu. 
- [ ] Make appropriate changes in the initialization Code (constructor) - such that the nodes are spaced accordingly.
- [ ] Make appropriate changes in `customSave` function

@HypheX do you feel a choice between 1 and 2 square gap is enough, or would you prefer more?

**Comment by HypheX** [comment]
I think a larger gap choice would be better. Many circuits have gaps of 15 or more, and the wiring gets really crazy in small spaces.

**Comment by ME-ON1** [comment]
is this issue open to be taken?? GSSOC19

**Comment by armudgal** [comment]
@ME-ON1 Please go forward.

**Comment by HypheX** [comment]
Has something similar to this been implemented yet?

**Comment by satu0king** [comment]
> Has something similar to this been implemented yet?

No. It is actually quite difficult to introduce now as there should be backward compatibility as well.

**Comment by Parikshit-Hooda** [comment]
@HypheX Whats the progress on this? This issue can be taken under Google Code In-2019 as no PR has been raised yet. What say @satu0king @ankitkataria . Perhaps

**Comment by pranavmodx** [comment]
Is this issue still up? If yes, I would like to take it up.
