### ISSUE TITLE
Indicate that Getting Started [in Navbar] is a dropdown 

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1655]
**Describe the bug**
The Getting Started nav-link in the navbar is a dropdown but the same isn't indicated.
![image](https://user-images.githubusercontent.com/16988558/93362006-1e2df300-f863-11ea-9542-0b6c3486ea10.png)

**Expected behavior**
A down arrow to indicate that it is, in fact, a dropdown 

**Are you working on this issue? (Yes/No)**
No

**Comment by siddhant2611** [comment]
can I work on this?

**Comment by DarthCucumber** [comment]
Hello I think someone is working on this but as I'm new into open source contribution I want to work on this so that I get the idea. If someone is already working please continue and you can make a pull request. I am working on this issue locally just to learn. I got stuck at a point. can you tell me which js file deals with the toggle dropdown. It'll be of great help.

**Comment by nitin10s** [comment]
@siddhant2611 should ideally be solving this.

**Comment by DarthCucumber** [comment]
> @siddhant2611 should ideally be solving this.

Okay sure. So you'll be making the pull request?

**Comment by DarthCucumber** [comment]
> @siddhant2611 should ideally be solving this.

okay sure no problem.

**Comment by Creatoon** [comment]
is it still open?

**Comment by DarthCucumber** [comment]
> is it still open? 

Yes I guess. I already fixed the issue but someone is already working on it. If he drops I'll make a PR. You can search for some other issue.

**Comment by reshma-avvaru** [comment]
is it still open

**Comment by rohan2734** [comment]
@nitin10s @satu0king   I have an idea, should i  work on this?
