### ISSUE TITLE
Delay 0 on non input/output components is possible

### ISSUE THREAD

**Issue by Comerstar** [CircuitVerse/CircuitVerse#2341]
**Describe the bug**
Non input/components can be set to have delay 0, and will behave as though they have delay 0. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Place down a component
2. Set its delay to 0
3. The component will behave as though it has delay 0
4. Saving or copying another component will reset the delay to 10

**Expected behaviour**
Since a component cannot be saved with delay 0, it should not be able to be given delay 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/67338307/126051508-fa1aef7d-9b7d-4d53-8a58-eb64a5fe3b49.png)

**Device Information:**
 - OS: Windows 10
 - Browser: Chrome

Are you working on this issue? No

**Comment by Palaksharma23** [comment]
i would love to work on this issue , can mentors please assign it to me ?

**Comment by TildaDares** [comment]
Hi @Palaksharma23, are you still working on this issue?

**Comment by Palaksharma23** [comment]
@TildaDares you can go ahead 👍

**Comment by TildaDares** [comment]
Hi @Palaksharma23, do you know what file I need to add this change to?

**Comment by gr455** [comment]
Hi Palak and Tilda, You might want to check [this line](https://github.com/CircuitVerse/CircuitVerse/blob/master/simulator/src/data/load.js#L45). This file is used to load the circuit from the saved data.
When `data.propagationDelay` is 0, this line will yeild `obj.propagationDelay` instead of `data.propagationDelay`.  You will have to add a case to allow `data.propagationDelay = 0`.
