### ISSUE TITLE
Unable to save an empty project

### ISSUE THREAD

**Issue by SunYiZheXinKe** [CircuitVerse/CircuitVerse#262]
Saving an empty project produces an error.

Create a new project, click 'save online', enter a project name, and see the error.

(Not working on this issue)

**Comment by ankitkataria** [comment]
The problem seems to be [here](https://github.com/CircuitVerse/CircuitVerse/blob/master/app/controllers/simulator_controller.rb#L63) 
When the circuit is empty, then `data_url` is `data:,`, it otherwise is `data:image/jpeg;base64,<actual_data>`. We'll need to check if `<actual_data>` is empty and save  maybe a custom image that says "No Preview Available" for the circuit. This will be required for both create and update methods in simulator_controller.

**Comment by theredcap** [comment]
Ok, I'll try to work on this issue

**Comment by SunYiZheXinKe** [comment]
One more thing to notice:
The bug only occurs when the empty circuit is currently selected. If you save the project while editing other circuits, it works fine even if there is empty circuit in the project.

**Comment by prajapatgautam1999** [comment]
@SunYiZheXinKe @ankitkataria I would to to work on this issue.

**Comment by Amansingla97** [comment]
@prajapatgautam1999 already done waiting it to get merged
