### ISSUE TITLE
Share link directly via social media functionality in group invite link

### ISSUE THREAD

**Issue by Palaksharma23** [CircuitVerse/CircuitVerse#2766]
![image](https://user-images.githubusercontent.com/87171452/148640711-675a6e45-3d09-4bd5-8c9b-86eb8b1e15cd.png)
I think we should add a button to share link via other social media icons just like we do on other platforms like youtube 

**Are you working on this? (Yes/No)**
Yes , i am working on this issue and will raise a pr soon

**Comment by vedant-jain03** [comment]
@Palaksharma23 I think that mentor doesn't want to post the invitation link on social media because:
- token has an expiry date of 12 days
- I think that it is an inappropriate way to share the link on social media as students are going to access it.
Although it is my point of view, WDYT @tachyons @ayan-biswas0412 @gr455 ?

**Comment by ayan-biswas0412** [comment]
> @Palaksharma23 I think that mentor doesn't want to post the invitation link on social media because:
> 
> * token has an expiry date of 12 days
> * I think that it is an inappropriate way to share the link on social media as other connections of mentors can access it.
> 
> Although it is my point of view, WDYT @tachyons @ayan-biswas0412 @gr455 ?

I also think that direct sharing on social media has a lot's of negative effects on the group itself, like spamming and unnecessary joining of lot's of members and also group link has a finite expiry time so sharing will not be a good choice
