### ISSUE TITLE
README should be updated it look outdated 

### ISSUE THREAD

**Issue by dhruvaop** [CircuitVerse/CircuitVerse#3353]
**Is your feature request related to a problem? Please describe.**
As I have seen many open source project they look more attractive and easy to use for beginners. 

**Describe the solution you'd like**
Add more section in the README should be beneficial for newbies 

**Describe alternatives you've considered**
Adding section like support and workflow

**Are you working on this? (Yes/No)**
Yes

**Comment by vedant-jain03** [comment]
cc @CircuitVerse/circuitverse-core-team

**Comment by dhruvaop** [comment]
Cc ?

**Comment by vedant-z** [comment]
@dhruvaop May I work on this as well?

**Comment by dhruvaop** [comment]
Hey @vedant-z  I am actively working on this Issue, you can pick another issue, Thanks.

**Comment by dhruvaop** [comment]
@vedant-jain03 I have send a PR please have a look

**Comment by vedant-jain03** [comment]
@dhruvaop I don't find this as practical.
Could you elaborate on what perspectives you think the readme should get updated as you mentioned "more attractive"?

Again I am saying kindly read the contribution guidelines before making the PR.
Let the core-team approve whether the issue is valid or not!

**Comment by dhruvaop** [comment]
Ok no issues

**Comment by vedant-jain03** [comment]
> Ok no issues

Also, we recommend discussing the issue in the slack #community channel as that is our platform for discussions!
You can ask your doubts or anything related to issues/pr/suggestions!

**Comment by tachyons** [comment]
We had too many things in the readme file before, it started to clutter with adding setup instructions for different operating systems, that is why we moved them to different pages and linked from readme. Ideas to improve readme files are welcome, but we can't simply imitate other projects due to the constraints we have.
