### ISSUE TITLE
Allow to preset EEPROM content

### ISSUE THREAD

**Issue by creack** [CircuitVerse/CircuitVerse#359]
**Is your feature request related to a problem? Please describe.**

Trying to model a circuit relying on EEPROM but doesn't seem possible as we can't change the content of it.

**Describe the solution you'd like**
A popup when clicking the eeprom or a menu item in right click or a link in the properties.
The UI could be similar to the ROM, based on the number of address and word size.

**Describe alternatives you've considered**
Seems possible by saving offline, updating the state in local storage and loading again, but Logisim as an alternative is easier.

**Are you working on this? (Yes/No)**
No

**Comment by fpintos** [comment]
Hi @creack ,

You can write to the EEPROM by setting its W pin to 1 and then it will save the value of the D pin in the address specified by the A pin. The idea is that you program the EEPROM using the circuit itself, as you would do with a "real" EEPROM and its data will persist when you save the project. The same goes for the RAM, except the RAM will not persist its data.

Here is a sample circuit that writes and then reads from the EEPROM:
https://circuitverse.org/users/1935/projects/13970

A UI to populate an EEPROM to get started with it quickly without a full blown circuit would be interesting indeed, although it would likely have to depart from the ROM model, since EEPROMs can be a lot larger.

You are correct that it is possible to edit the data in the saved project; in fact, my quick-and-dirty suggestion at this point is to copy the EEPROM to the clipboard, paste it in your favorite editor, update the resulting JSON with the data you want, then copy the text and paste it back into CircuitVerse.

**Comment by creack** [comment]
Copy/paste did the trick for now. However, I disagree with the use case. a "real" eeprom is most of the time programmed on the side using an eeprom programmer then inserted into a circuit.
I'm not UI expert, but having some kind of ways to preload the eeprom content would be great.
In the meantime, I updated my eeprom programmer to dump a json file that I can copy/paste.

**Comment by tachyons** [comment]
cc @gr455
