### ISSUE TITLE
🐞 Bug: `view` button is not aligned in user search menu 

### ISSUE THREAD

**Issue by theslowdeveloper** [CircuitVerse/CircuitVerse#4163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The view button in user search menu is not aligned, there is a default margin restricting it from begin aligned
![Screenshot from 2023-10-10 17-57-47](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/3d9cf842-7094-49b8-be99-8aac26739587)

### Steps To Reproduce

1. Go to https://circuitverse.org/search?resource=Users&q=&button=Submit
2. See the aligned of view button with other stats 

### Expected Behavior

The View button should be aligned 
![image](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/bee5e079-cf21-4f54-b796-cba5591cfa59)

### Device Information [optional]

```markdown
- OS: Linux Mint 21
- Browser: Brave
- version: 1.58
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
Hi @theslowdeveloper 
This issue was due to the margin in `primary-button` class
In a recent PR #4141 this margin has been removed. So the issue in your PR have already fixed. 
Just for context, The production website is deployed manually, so whatever changes happening on this repository will not take effect immediately

If you feel the issue has fixed, close this issue.
