### ISSUE TITLE
Text tool not behaving well with hotkeys

### ISSUE THREAD

**Issue by phyzicist** [CircuitVerse/CircuitVerse#445]
**Describe the bug**
When typing out text in a Text element of Circuitverse, hotkeys result in weird blended behavior. E.g. typing Ctrl + C does copy the element, but also adds a "c" to the end of the text box. Weirdness for Ctrl + Z, Delete, apostrophe, etc.

**To Reproduce**
1. Make a Text element.
2. Type anything in the box.
2. Deselect it.
3. Reselect it.
4. Type Ctrl + C. Notice how "c" is appended to the text box.
5. Paste with Ctrl + V. Notice how the pasted text box also has the extra c.

**Expected behavior**
I feel that the best solution is to treat **typing within** a text box differently than **selecting** a text box.
1. On first placement of text box, enter **typing mode**. This could be indicated with a blinking cursor.
2. Exit **typing mode** by clicking anywhere else in circuit.
3. Any time later, single click on the text box to enter **selected mode**. As with other circuit elements, this **selected mode** could be indicated by changing the color of the text box.
4. Or, any time later, double-click the text box to re-enter **typing mode**. As I mentioned earlier, this can be indicated with a blinking cursor (and the original color).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 69.0

**Additional context**
I often delete my own text boxes accidentally by typing "Delete" key.

**Are you working on this issue? (Yes/No)**
No

**Comment by NavonilDas** [comment]
I am working on it.

**Comment by shubhankarsharma00** [comment]
@satu0king can we reopen this?

**Comment by pulkit-30** [comment]
Hey !,
I tried to reproduce this issue with the Text box in CV, 
I write Hello and tried to copy and paste using hotkeys 

```
cmd+c and cmd+v
```
it adds c and v at the end of Hello and it doesn't copy and paste the text box.


https://user-images.githubusercontent.com/76155456/147568572-20385f17-e262-4eee-8714-4a3fc49ae3f9.mov


Expected behavior:
It should Copy the Text box and create a new one with the same text. 

https://user-images.githubusercontent.com/76155456/147569217-534ee4ea-d339-4748-95a4-3ba72b7779ae.mov

cc: @tachyons @nitin10s @shubhankarsharma00

**Comment by tachyons** [comment]
👍
