### ISSUE TITLE
🐞 Bug: Text area to add collaborator is too small to enter text

### ISSUE THREAD

**Issue by Miran-Firdausi** [CircuitVerse/CircuitVerse#4454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The text input area for add a collaborator menu is too small to enter anything, making it unable to use.

https://github.com/CircuitVerse/CircuitVerse/assets/75238590/ef8b6989-c9af-4ee2-8e28-ab7465f26bc1

### Steps To Reproduce

1. Open any project.
2. Click on "+ Add a collaborator" button
3. Try typing in the text box

### Expected Behavior

The text input area needs to be adjusted according to the width of the box.

### Device Information [optional]

os: ubuntu 20.04
browser: brave

### Are you working on this issue?

No

**Comment by fillingtothemomo** [comment]
@Miran-Firdausi it is working fine on my system ,what browser are you using?

**Comment by Miran-Firdausi** [comment]
@fillingtothemomo its brave on ubuntu.

**Comment by tanmoysrt** [comment]
Hi @Miran-Firdausi this issue has been actually fixed.
![image](https://github.com/CircuitVerse/CircuitVerse/assets/57363826/8838d743-8aab-4132-bc50-4a2d7c289336)

The production may haven't latest codebase, that's why the issue is still there on website. 

If you find the issue in current codebase, you can reopen the issue.
