### ISSUE TITLE
🐞 Bug: Error After Click "Start working" Twice

### ISSUE THREAD

**Issue by Kiran-pande-30** [CircuitVerse/CircuitVerse#4819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. If a user starts to work on the assignment. After going back by browser btn, the `start working` has not changed to `View your work`. After click start working button twice it throws the error.

https://github.com/CircuitVerse/CircuitVerse/assets/105718863/7a034a6e-4f89-444b-9d15-d4f221dab02a

### Steps To Reproduce

1. Go to My Groups
3. Add assignments to the group as a mentor
4. Add Members.
5. Go through the Assignments section as member.

### Expected Behavior
1. After Clicking the` start working` button twice, the user should be redirected to already created project.

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Chrome
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
1. Until unless mentor have closed the assignment, he can't put the grade. It's expected behaviour.
2. Actually you are clicking on the `start working` button twice. When you click `start working` it will create a project and now if you check the page it should have a button `view your work`. but, you are going back by browser back button and clicking on `start working` and that's raise the error as you have already created and not authorized to create a new one.

-----

You may close this issue & create couple of seperate issues for each topic seperately so that other contributors can also work on.
1. In grade submission, don't show the `Grades and remarks` and `grade details` section, until unless mentor has clicked any of the student name from the list. Ref -
![image](https://github.com/CircuitVerse/CircuitVerse/assets/57363826/0f1e3411-3a0d-4976-9670-c863c7020403)
2. After clicking the student name, pre-fill the inputs with the already recorded grade and remarks. Currently it comes only in a below card.
3. If a student click on `start working` button again, rather than throwing `not authorized` error, redirect him to already created project.
