### ISSUE TITLE
Remove re-entering of email in forgot password

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#489]
**Is your feature request related to a problem? Please describe.**
When user entered email and then clicked forgot password, the forgot password instructions should be directly sent instead of asking for email again.

**Describe the solution you'd like**
The same email parameter should be linked with the forgot password email parameter.

**Additional context**
Find below the screenshot of the above described feature.
![Fp](https://user-images.githubusercontent.com/42520146/68011108-6de7e800-fcac-11e9-8b6d-31d497fc97d6.PNG)

**Comment by Shivansh2407** [comment]
This is not suitable for those users who have not entered their email in the Email Field . When there is no email in the field and user clicks on the Forgot Password Link then it would give error. We could fix it as if the user has entered the email in the field and clicked Forgot Password then it should not show the Forgot Password Page otherwise it shows. Would like to hear what you think about this @sakshi1499 and @tachyons ?

**Comment by Ananthavijay** [comment]
Nope, when the user does not enter user's mail id the forgot password page should not have any email id but if the user enter the email it should be carried to forgot password page

**Comment by sakshi1499** [comment]
@Shivansh2407 I would second @Ananthavijay . That is exactly what I had in mind when I created this issue. You can however share your vision, in case you want to add something more.

**Comment by Shivansh2407** [comment]
Can I work on this @sakshi1499 then?

**Comment by sakshi1499** [comment]
I think this task was dealt with, in GCI. Please confirm once. If not, you are most welcome to contribute to it. @Shivansh2407

**Comment by Ananthavijay** [comment]
I think this was not put up as a task in GCI @sakshi1499

**Comment by tachyons** [comment]
GCI is already over, So all the issues are now free to take

**Comment by Shivansh2407** [comment]
Cool thanks @tachyons
