### ISSUE TITLE
ScrollBars missing in Simulator

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#567]
**Describe the bug**
There are no scroll bars in the simulator window for better navigation. 

**To Reproduce**
1. Go to 'Simulator window
2. See error

**Expected behavior**
Since the swipe up/down actions zoom in and out of the window rather than scrolling through the window; it would be good to have explicit scroll bars present on sides of the circuit window.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68359073-a66e4280-0140-11ea-82da-8c16ac466fc5.png)

**Comment by nitin10s** [comment]
What do you want to navigate? I tried designing a circuit and observed that I stay on the same window state for most of the time and use the zoom-in zoom-out feature. I think the navigation works perfectly fine.
My suggestion - Record your own video while trying to design a few circuits. Observe when or if you feel the need for scrolling up and down the circuits. Post the video because it'll be great for the developers to understand and observe how other users use the tool.

If they feel the need, they can try out the same test on more users to decide what'll be best to do.😄
