### ISSUE TITLE
Remove unnecessary 'div'

### ISSUE THREAD

**Issue by plxity** [CircuitVerse/CircuitVerse#578]
**Describe the bug**
An unnecessary `div` is present which creates extra in the mobile view.
![Screenshot from 2019-11-08 19-52-52](https://user-images.githubusercontent.com/28510494/68483456-9bf79a00-0261-11ea-88fc-26c8a4465cab.png)

**Expected behaviour**
Removing that `div` would solve the issue.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Are you working on this issue? (Yes/No)**
For GCI

**Comment by aayush-05** [comment]
I think rather than removing the div element completely, a better option would be to use media queries and add a breakpoint. Because the div element is necessary in the desktop view to maintain space.

![image](https://user-images.githubusercontent.com/47032027/68506518-cceec380-028f-11ea-8a02-5547a2c9b6a0.png)

**Comment by aayush-05** [comment]
**Duplicate Issue**
This issue has already been raised #528 

You can close this one.
