### ISSUE TITLE
Backspace is not working in the text input field for boolean logic table. 

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerse#602]
**Describe the bug**

Backspace is not working for the text input field at the Combinational Analysis > BooleanLogicTable link at simulator.

**To Reproduce**
1. Go to 'https://circuitverse.org/simulator/'
2. Click on 'Tools'
3. Select 'Combinational Analysis'
4. Input some text, try to use backspace.

**Expected behaviour**

The text input should take normal text input, it may have some restrictions like using only alphabets but backspace should be allowed.

**Screenshots**

![backspace](https://user-images.githubusercontent.com/42115530/68548853-685e7080-0417-11ea-84be-42e0008e2feb.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.97

**Are you working on this issue? (Yes/No)**
No, For GCI students.

**Comment by aayush-05** [comment]
It is not working for the Output names as well.

**Comment by PragatiVerma18** [comment]
Yeah, by text input field I meant the HTML input tag, so basically, I meant for both input and output.

**Comment by aayush-05** [comment]
Oh, okay. I misunderstood.

**Comment by Shivansh2407** [comment]
Please reopen this issue @tachyons . I have a PR pending to fix this issue.

**Comment by satu0king** [comment]
#121, #322, #326, #602 are related issues. 
@Shivansh2407 

The issue is that on mac backspace is also delete key (backspace and delete key are combined in mac). Actual delete is `fn + backspace` but not all the users are aware of it. This raises a weird problem, backspace in text boxes is actually backspace and not delete. For some annoying reason I haven't been able to find a solution to this even though I expect a simple solution to be present. Note that this backspace issue is present every where -> property menu, combinational analysis etc.

**Comment by KaustubhDamania** [comment]
@satu0king What if the interaction with simulator area is disabled when any dialog is open? So when a dialog is open, such as combination analysis, then the user won't be able to add new elements in the simulator area.
