### ISSUE TITLE
"Multiple Input" solutions

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#61]
Normally, having multiple inputs into one wire causes some bizarre results. I'll be honest, I don't like the current behavior, and how multiple inputs are handled (or rather, not). I believe that multiple inputs should then OR compare all of the inputs, and treat it as such. Essentially, wires should act as OR gates if more than one input occurs. This makes more sense to me, and would also make wiring a bit less finicky. If this is done due to a technical limitation, that would make sense. If this can be solved otherwise, please do so.

**Comment by satu0king** [comment]
No, actually multiple inputs should not be an OR on the wires. If that is what you actually want, then simply put it behind an OrGate before putting it into the wire. 

> If this is done due to a technical limitation, that would make sense. If this can be solved otherwise, please do so.

No, it is not done due to a technical limitation. Two input sources should not drive a bus to 2 different values. What you are suggesting is plain short ciruiting of circuits. 

However I think what you actually need is a TriState buffer. Take a look into it.
