### ISSUE TITLE
"for ever" Typo in app/view/logix/contribute.html.erb

### ISSUE THREAD

**Issue by ericsheng495** [CircuitVerse/CircuitVerse#680]
**Describe the bug**

**To Reproduce**

**Expected behavior**
"For ever" Typo in app/view/logix/contribute.html.erb. Will replace "for ever" with "forever" in the file. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44331935/70112098-39e44780-1609-11ea-9ac0-4fa8c3887c61.png)

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

**Comment by sakshi1499** [comment]
@ericsheng495 I don't think we need another issue of this. We have a general typo issue raised and if you want to make a change please update it in your existed Pull Request only, We'll review it there itself.

**Comment by ericsheng495** [comment]
How should I update these change in the existing Pull Request?

**Comment by sakshi1499** [comment]
@ericsheng495 You know the exact path of this right? So you can go and update changes in this particular file. Then you can update it in your existing patch. Otherwise you can open a completely new pr with all the changes in one place and close the existing one. Also, please check if someone has made these changes in some other PR, I think I have seen this issue with someone else too.
