### ISSUE TITLE
Bulk mail

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#7]
The organisation needs a way to send bulk mail to all users. Ideally we should be able to use transactional email service like mailchimp. Alternatively we can maintain our own subscription system (not recommended).

**Comment by garry329** [comment]
I would like to work on this issue.I will start looking into email services.

**Comment by satu0king** [comment]
Do check for email services, however the organization currently doesn't have any funds to actually pay for a subscription service. Maybe, if you can find one that gives opensource/non-profit/educational organizations subscriptions for free, then awesome.

**Comment by armudgal** [comment]
Hi @garry329, are you working on this? If yes, what are the updates.

**Comment by ankitkataria** [comment]
I think it is possible to implement this through a simple ruby mail script that iterates through all the users and sends them emails. 
In order to reduce the run time of the script, we can look into dividing the users into chunks and processing chunks in different threads, we can experiment with the chunk size and the no of email queues to see which one responds with the best result.

**Comment by satu0king** [comment]
> In order to reduce the run time of the script, we can look into dividing the users into chunks and processing chunks in different threads, we can experiment with the chunk size and the no of email queues to see which one responds with the best result.

Yes, these are my thoughts as well. We are currently using yandex as our mail provider. Which surprisingly gives free email service for custom domain and as far as I can see it isn't against their user policy to use this email as a server email. I couldn't even find any restrictions regarding the same. However, based on articles and blogs on the internet it is best to use a mailing service.

**Comment by ankitkataria** [comment]
> We can implement that for now, there are quite a few announcements that are to be done in CircuitVerse and we could do with a quick implementation.

Great, @garry329 Let us know if you're still working on it. Also don't hesistate to ask for help if required. :wink:

**Comment by garry329** [comment]
@satu0king @armudgal according to plans provided by email services:
- we can have a service like mailgun or mailchimp which provide about 10,000 emails per month on their free plans.
- services like sendgrid and sendinblue providing few hundered emails per day.
Now, i don't think either of the above plans would suffice.
So, for now we can go with a script as suggested to roll out some quick announcements.
Can you please tell me what needs to be done now?

**Comment by armudgal** [comment]
I have worked previously on mass mailers and there are too many factor to consider such as multi-threading(puma) and when there is parallelism, there are cases when the mails are not sent properly or end up in spam. I really don't see the point of reinventing the wheel by writing our own script. 

**Suggestion** : We go forward with mailchimp or mailgun, because setting them up won't take much time, if that doesn't satisfy our needs we can look through options for writing a massmailer ourself. 
Thoughts?

**Comment by tachyons** [comment]
I second @armudgal

**Comment by satu0king** [comment]
@tachyons @armudgal You are right. We need to use something like mailchimp and mailgun. But not right now, maybe someone can send a PR and we can keep it pending till we acquire funds for the same.

**Comment by tachyons** [comment]
Mailchimp's free plan must be  enough for our usecase https://mailchimp.com/help/about-the-forever-free-plan/

**Comment by satu0king** [comment]
I had already seen this, the free plan allows it to be free until 2000 subscribers, we have already crossed 4000 users!

**Comment by tachyons** [comment]
.

**Comment by satu0king** [comment]
An inbuilt solution has been implemented in this PR #423. However, this may not scale and we need to use a 3rd party API. As of now we haven't sent a single email blast using this service, so it is untested. There are over 20,000 subscribers currently.

**Comment by satu0king** [comment]
We need to migrate everything, so closing this PR
