### ISSUE TITLE
Have sharing preferences default to "private"

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#70]
Too many people save stuff online, and leave the sharing perms on public. This clogs up the "recent circuits" area with incomplete ciruits. This should be an easy fix, at least I hope :P 

If I can be bothered, I'll make a fork with this patch and then make a pull request to make it easier for yah.

**Comment by satu0king** [comment]
> This clogs up the "recent circuits" area with incomplete circuits. 
This has to be fixed by improving the featured circuits section and maybe adding another trending now section. The trending now to be dynamic based on views, comments, and likes. 

Since CircuitVerse is free and open source, the platform should not encourage circuits to be private. The only reason it has private circuits is so that students and professors can hide assignments from each other.
