### ISSUE TITLE
RAM component

### ISSUE THREAD

**Issue by superstewie** [CircuitVerse/CircuitVerse#81]
I believe a RAM component should be made. When working with large RAM, weird errors start to occur around 16k bytes. I tried two methods of building RAM, one method which uses progressively larger matrices of 8 bit registers which fails around 16k bytes, and one method which uses multiples of the circuit below:
![capture](https://user-images.githubusercontent.com/36019929/50452754-b0f56400-0901-11e9-932e-040360472e43.PNG)
Which uses a 32 bit register and some multiplexers to store 4 bytes in a single register. It fails around 16 bytes.

Some of the failures are very, interesting:
![capture1](https://user-images.githubusercontent.com/36019929/50452947-d040c100-0902-11e9-81e5-48905e8b1e1e.PNG)

Where the minimap shows that there are 4 subcircuits, but the editor only shows two. Other failures have included red screens, or just plain old extreme lagging.

A RAM component with a configurable address width would be very nice.

**Comment by satu0king** [comment]
Yes, a RAM component is needed.

**Comment by satu0king** [comment]
The minimap problem might simply be an update delay. As for the lagging, try and use subcircuits as much as possible. The lagging is due to the rendering of the circuit and not the simulation of the circuit. 

Other failures have included red screens. This is disturbing, could you give a situation when this happened.

**Comment by HypheX** [comment]
Me and blane have tried doing huge RAM's before, but even if we used

It would be lovely to see a bit width property and a separate "address bit width" property, allowing for the customization of the RAM's size to its full extent.

However, one has to keep in mind that the maximum bit width possible is 32, possibly due to limitations with the browsers, only allowing integers up to 2^32-1.
A fix for this is storing the states of multi-bit wires as arrays and not as integers, as it is currently done.

**Comment by superstewie** [comment]
>  As for the lagging, try and use subcircuits as much as possible. The lagging is due to the rendering of the circuit and not the simulation of the circuit.

> Other failures have included red screens. This is disturbing, could you give a situation when this happened.

The largest circuit was built by using 4 eight bit registers, with a 2 control bit demux on the input and mux output. Then nesting those four at a time. In one situation, when using Firefox (I have also tried multiple browsers), I placed one of the subcircuits containing 4K bytes, then copy/pasted it once, and then when I pasted a selection of those two to create a 16K group of RAM, the redscreen occurred. Unfortunately I cannot reproduce it, and I did not get a screen shot of it.

> An even better fix would be to use 1 integer for every 32 bits in a wire, allowing for virtually unlimited bit widths without changing the code that much.

IMO a 32 bit address space is plenty wide for anything that would ever be created with this. Especially until we get an HDL tool.

**Comment by satu0king** [comment]
> I placed one of the subcircuits containing 4K bytes, then copy/pasted it once, and then when I pasted a selection of those two to create a 16K group of RAM, the redscreen occurred. 

@superstewie not sure why this would happen. The red screen occurs when the rendering fails. 

> IMO a 32 bit address space is plenty wide for anything that would ever be created with this. Especially until we get an HDL tool.

@HypheX, 32 bit address space is actually pretty high. There are still many computers around that use a 32-bit architecture. With 32 bits, you can actually address 4294967296 locations. If each location is 1 byte, then you can address 4 GB.

**Comment by HypheX** [comment]
I am aware, I was mainly talking about bitwidth issues, not specifically about address space, wires break if you attempt to use a bitwidth of 33 or higher.

**Comment by blane1257** [comment]
This is a really great idea! similarly the ability to customize the address and byte bitwidth of the ROM would be a nice feature, but understandably difficult due to the need to have the values displayed on top of it

**Comment by fpintos** [comment]
Hi, I've created a PR with a RAM component that should address these issues.

Since it is a built-in component it will not have the 'large RAM' issue we saw, which I believe was due to the number of events in the simulation queue when building the RAM with flip-flops.

I've also made the address and data widths configurable. Addresses can go up to 20 bits and data to 32 bits as usual. I chose 20 bits for address to keep browsers happy, otherwise memory allocation would go way high. That is 1M of address space, for a total of 4MB (if using 32-bit data). I suppose one can still multiplex if one needs more memory than that or we can lift the 20-bit restriction if needed, but, you know...the browser might meltdown. :-) 

In addition to the usual ADDRESS/DI/WRITE/DO pins, I've included a RESET (to zero the whole thing in one shot) and a CORE DUMP pin, which dumps the raw data into the browser's console so one can view the full contents of the RAM.

Perhaps a future improvement would be download button, which would produce a file with the contents of the RAM, although for that I imagine one might want to specify start/length values. Oh, shot...I just thought of a way to do it, with a cheat: we can have a separate component, FileDownload with the start/length pins, which would connect to a "DMA" pin in the RAM - this would be a fake pin, no data would actually flow thru it during the simulation, but internally the FileDownload component can reach out to the connected RAM component and directly read its data!

**Comment by satu0king** [comment]
> Perhaps a future improvement would be download button, which would produce a file with the contents of the RAM, although for that I imagine one might want to specify start/length values. Oh, shot...I just thought of a way to do it, with a cheat: we can have a separate component, FileDownload with the start/length pins, which would connect to a "DMA" pin in the RAM - this would be a fake pin, no data would actually flow thru it during the simulation, but internally the FileDownload component can reach out to the connected RAM component and directly read its data!

I think an easier and more elegant way to implement file download is to simply have a button in the properties which will when clicked, will download the data. This is great if you were planning to use the file download option mainly for debugging, but if you were to use it a way for end users to say save state etc, then this may not be the best way to go.
